# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EPICS Hardware Platform Support
email: jeonghan.lee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains a list of the modules that provide Hardware Support for use within an IOC, with links to the current maintainer and the web-site for each if it exists.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://epics-hw.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jeonghanlee

# Build settings
markdown: kramdown
